#include "ccompiler/token.h"

static const char *const cc_token_names[CC_TOKEN_KIND_COUNT] = {
    [CC_TOKEN_EOF] = "eof",
    [CC_TOKEN_INVALID] = "invalid",
    [CC_TOKEN_IDENTIFIER] = "identifier",
    [CC_TOKEN_INTEGER_LITERAL] = "integer",
    [CC_TOKEN_FLOAT_LITERAL] = "float",
    [CC_TOKEN_STRING_LITERAL] = "string",
    [CC_TOKEN_CHAR_LITERAL] = "char",
    [CC_TOKEN_KEYWORD_BEGIN] = "<keyword_begin>",
    [CC_TOKEN_KW_AUTO] = "kw_auto",
    [CC_TOKEN_KW_BREAK] = "kw_break",
    [CC_TOKEN_KW_CASE] = "kw_case",
    [CC_TOKEN_KW_CHAR] = "kw_char",
    [CC_TOKEN_KW_CONST] = "kw_const",
    [CC_TOKEN_KW_CONTINUE] = "kw_continue",
    [CC_TOKEN_KW_DEFAULT] = "kw_default",
    [CC_TOKEN_KW_DO] = "kw_do",
    [CC_TOKEN_KW_DOUBLE] = "kw_double",
    [CC_TOKEN_KW_ELSE] = "kw_else",
    [CC_TOKEN_KW_ENUM] = "kw_enum",
    [CC_TOKEN_KW_EXTERN] = "kw_extern",
    [CC_TOKEN_KW_FLOAT] = "kw_float",
    [CC_TOKEN_KW_FOR] = "kw_for",
    [CC_TOKEN_KW_GOTO] = "kw_goto",
    [CC_TOKEN_KW_IF] = "kw_if",
    [CC_TOKEN_KW_INLINE] = "kw_inline",
    [CC_TOKEN_KW_INT] = "kw_int",
    [CC_TOKEN_KW_LONG] = "kw_long",
    [CC_TOKEN_KW_REGISTER] = "kw_register",
    [CC_TOKEN_KW_RESTRICT] = "kw_restrict",
    [CC_TOKEN_KW_RETURN] = "kw_return",
    [CC_TOKEN_KW_SHORT] = "kw_short",
    [CC_TOKEN_KW_SIGNED] = "kw_signed",
    [CC_TOKEN_KW_SIZEOF] = "kw_sizeof",
    [CC_TOKEN_KW_STATIC] = "kw_static",
    [CC_TOKEN_KW_STRUCT] = "kw_struct",
    [CC_TOKEN_KW_SWITCH] = "kw_switch",
    [CC_TOKEN_KW_TYPEDEF] = "kw_typedef",
    [CC_TOKEN_KW_UNION] = "kw_union",
    [CC_TOKEN_KW_UNSIGNED] = "kw_unsigned",
    [CC_TOKEN_KW_VOID] = "kw_void",
    [CC_TOKEN_KW_VOLATILE] = "kw_volatile",
    [CC_TOKEN_KW_WHILE] = "kw_while",
    [CC_TOKEN_KW_ALIGNAS] = "kw__Alignas",
    [CC_TOKEN_KW_ALIGNOF] = "kw__Alignof",
    [CC_TOKEN_KW_ATOMIC] = "kw__Atomic",
    [CC_TOKEN_KW_BOOL] = "kw__Bool",
    [CC_TOKEN_KW_COMPLEX] = "kw__Complex",
    [CC_TOKEN_KW_GENERIC] = "kw__Generic",
    [CC_TOKEN_KW_IMAGINARY] = "kw__Imaginary",
    [CC_TOKEN_KW_NORETURN] = "kw__Noreturn",
    [CC_TOKEN_KW_STATIC_ASSERT] = "kw__Static_assert",
    [CC_TOKEN_KW_THREAD_LOCAL] = "kw__Thread_local",
    [CC_TOKEN_KEYWORD_END] = "<keyword_end>",
    [CC_TOKEN_PUNCTUATOR_BEGIN] = "<punctuator_begin>",
    [CC_TOKEN_LPAREN] = "lparen",
    [CC_TOKEN_RPAREN] = "rparen",
    [CC_TOKEN_LBRACE] = "lbrace",
    [CC_TOKEN_RBRACE] = "rbrace",
    [CC_TOKEN_LBRACKET] = "lbracket",
    [CC_TOKEN_RBRACKET] = "rbracket",
    [CC_TOKEN_COMMA] = "comma",
    [CC_TOKEN_SEMICOLON] = "semicolon",
    [CC_TOKEN_COLON] = "colon",
    [CC_TOKEN_DOT] = "dot",
    [CC_TOKEN_ELLIPSIS] = "ellipsis",
    [CC_TOKEN_QUESTION] = "question",
    [CC_TOKEN_HASH] = "hash",
    [CC_TOKEN_HASH_HASH] = "hash_hash",
    [CC_TOKEN_ARROW] = "arrow",
    [CC_TOKEN_INCREMENT] = "increment",
    [CC_TOKEN_DECREMENT] = "decrement",
    [CC_TOKEN_PLUS] = "plus",
    [CC_TOKEN_MINUS] = "minus",
    [CC_TOKEN_STAR] = "star",
    [CC_TOKEN_SLASH] = "slash",
    [CC_TOKEN_PERCENT] = "percent",
    [CC_TOKEN_AMPERSAND] = "ampersand",
    [CC_TOKEN_PIPE] = "pipe",
    [CC_TOKEN_CARET] = "caret",
    [CC_TOKEN_TILDE] = "tilde",
    [CC_TOKEN_BANG] = "bang",
    [CC_TOKEN_ASSIGN] = "assign",
    [CC_TOKEN_PLUS_ASSIGN] = "plus_assign",
    [CC_TOKEN_MINUS_ASSIGN] = "minus_assign",
    [CC_TOKEN_STAR_ASSIGN] = "star_assign",
    [CC_TOKEN_SLASH_ASSIGN] = "slash_assign",
    [CC_TOKEN_PERCENT_ASSIGN] = "percent_assign",
    [CC_TOKEN_AMPERSAND_ASSIGN] = "ampersand_assign",
    [CC_TOKEN_PIPE_ASSIGN] = "pipe_assign",
    [CC_TOKEN_CARET_ASSIGN] = "caret_assign",
    [CC_TOKEN_LEFT_SHIFT] = "left_shift",
    [CC_TOKEN_RIGHT_SHIFT] = "right_shift",
    [CC_TOKEN_LEFT_SHIFT_ASSIGN] = "left_shift_assign",
    [CC_TOKEN_RIGHT_SHIFT_ASSIGN] = "right_shift_assign",
    [CC_TOKEN_LOGICAL_AND] = "logical_and",
    [CC_TOKEN_LOGICAL_OR] = "logical_or",
    [CC_TOKEN_EQUAL] = "equal",
    [CC_TOKEN_NOT_EQUAL] = "not_equal",
    [CC_TOKEN_LESS] = "less",
    [CC_TOKEN_LESS_EQUAL] = "less_equal",
    [CC_TOKEN_GREATER] = "greater",
    [CC_TOKEN_GREATER_EQUAL] = "greater_equal",
    [CC_TOKEN_PUNCTUATOR_END] = "<punctuator_end>",
};

const char *cc_token_kind_name(CCTokenKind kind) {
    if ((size_t)kind >= CC_TOKEN_KIND_COUNT || cc_token_names[kind] == NULL) {
        return "<unknown>";
    }

    return cc_token_names[kind];
}

bool cc_token_kind_is_keyword(CCTokenKind kind) {
    return kind > CC_TOKEN_KEYWORD_BEGIN && kind < CC_TOKEN_KEYWORD_END;
}

bool cc_token_kind_is_punctuator(CCTokenKind kind) {
    return kind > CC_TOKEN_PUNCTUATOR_BEGIN && kind < CC_TOKEN_PUNCTUATOR_END;
}
