#ifndef C-Compiler_TOKEN_H
#define C-Compiler_TOKEN_H

#include <stdbool.h>
#include <stddef.h>

typedef struct {
    size_t offset;
    size_t line;
    size_t column;
    size_t length;
} CCSpan;

typedef enum {
    CC_TOKEN_EOF,
    CC_TOKEN_INVALID,
    CC_TOKEN_IDENTIFIER,
    CC_TOKEN_INTEGER_LITERAL,
    CC_TOKEN_FLOAT_LITERAL,
    CC_TOKEN_STRING_LITERAL,
    CC_TOKEN_CHAR_LITERAL,

    CC_TOKEN_KEYWORD_BEGIN,
    CC_TOKEN_KW_AUTO,
    CC_TOKEN_KW_BREAK,
    CC_TOKEN_KW_CASE,
    CC_TOKEN_KW_CHAR,
    CC_TOKEN_KW_CONST,
    CC_TOKEN_KW_CONTINUE,
    CC_TOKEN_KW_DEFAULT,
    CC_TOKEN_KW_DO,
    CC_TOKEN_KW_DOUBLE,
    CC_TOKEN_KW_ELSE,
    CC_TOKEN_KW_ENUM,
    CC_TOKEN_KW_EXTERN,
    CC_TOKEN_KW_FLOAT,
    CC_TOKEN_KW_FOR,
    CC_TOKEN_KW_GOTO,
    CC_TOKEN_KW_IF,
    CC_TOKEN_KW_INLINE,
    CC_TOKEN_KW_INT,
    CC_TOKEN_KW_LONG,
    CC_TOKEN_KW_REGISTER,
    CC_TOKEN_KW_RESTRICT,
    CC_TOKEN_KW_RETURN,
    CC_TOKEN_KW_SHORT,
    CC_TOKEN_KW_SIGNED,
    CC_TOKEN_KW_SIZEOF,
    CC_TOKEN_KW_STATIC,
    CC_TOKEN_KW_STRUCT,
    CC_TOKEN_KW_SWITCH,
    CC_TOKEN_KW_TYPEDEF,
    CC_TOKEN_KW_UNION,
    CC_TOKEN_KW_UNSIGNED,
    CC_TOKEN_KW_VOID,
    CC_TOKEN_KW_VOLATILE,
    CC_TOKEN_KW_WHILE,
    CC_TOKEN_KW_ALIGNAS,
    CC_TOKEN_KW_ALIGNOF,
    CC_TOKEN_KW_ATOMIC,
    CC_TOKEN_KW_BOOL,
    CC_TOKEN_KW_COMPLEX,
    CC_TOKEN_KW_GENERIC,
    CC_TOKEN_KW_IMAGINARY,
    CC_TOKEN_KW_NORETURN,
    CC_TOKEN_KW_STATIC_ASSERT,
    CC_TOKEN_KW_THREAD_LOCAL,
    CC_TOKEN_KEYWORD_END,

    CC_TOKEN_PUNCTUATOR_BEGIN,
    CC_TOKEN_LPAREN,
    CC_TOKEN_RPAREN,
    CC_TOKEN_LBRACE,
    CC_TOKEN_RBRACE,
    CC_TOKEN_LBRACKET,
    CC_TOKEN_RBRACKET,
    CC_TOKEN_COMMA,
    CC_TOKEN_SEMICOLON,
    CC_TOKEN_COLON,
    CC_TOKEN_DOT,
    CC_TOKEN_ELLIPSIS,
    CC_TOKEN_QUESTION,
    CC_TOKEN_HASH,
    CC_TOKEN_HASH_HASH,
    CC_TOKEN_ARROW,
    CC_TOKEN_INCREMENT,
    CC_TOKEN_DECREMENT,
    CC_TOKEN_PLUS,
    CC_TOKEN_MINUS,
    CC_TOKEN_STAR,
    CC_TOKEN_SLASH,
    CC_TOKEN_PERCENT,
    CC_TOKEN_AMPERSAND,
    CC_TOKEN_PIPE,
    CC_TOKEN_CARET,
    CC_TOKEN_TILDE,
    CC_TOKEN_BANG,
    CC_TOKEN_ASSIGN,
    CC_TOKEN_PLUS_ASSIGN,
    CC_TOKEN_MINUS_ASSIGN,
    CC_TOKEN_STAR_ASSIGN,
    CC_TOKEN_SLASH_ASSIGN,
    CC_TOKEN_PERCENT_ASSIGN,
    CC_TOKEN_AMPERSAND_ASSIGN,
    CC_TOKEN_PIPE_ASSIGN,
    CC_TOKEN_CARET_ASSIGN,
    CC_TOKEN_LEFT_SHIFT,
    CC_TOKEN_RIGHT_SHIFT,
    CC_TOKEN_LEFT_SHIFT_ASSIGN,
    CC_TOKEN_RIGHT_SHIFT_ASSIGN,
    CC_TOKEN_LOGICAL_AND,
    CC_TOKEN_LOGICAL_OR,
    CC_TOKEN_EQUAL,
    CC_TOKEN_NOT_EQUAL,
    CC_TOKEN_LESS,
    CC_TOKEN_LESS_EQUAL,
    CC_TOKEN_GREATER,
    CC_TOKEN_GREATER_EQUAL,
    CC_TOKEN_PUNCTUATOR_END,

    CC_TOKEN_KIND_COUNT
} CCTokenKind;

typedef struct {
    CCTokenKind kind;
    CCSpan span;
} CCToken;

const char *cc_token_kind_name(CCTokenKind kind);
bool cc_token_kind_is_keyword(CCTokenKind kind);
bool cc_token_kind_is_punctuator(CCTokenKind kind);

#endif
